---
# Begin Windows tasks file
- name: Create a temp directory
  win_file:
    state: directory
    path: "{{ win_software_dest_folder }}"

- name: Pull installer from web
  become: yes
  win_get_url:
    url: "{{ win_software_url }}"
    dest: "{{ win_software_dest_folder }}\\{{ win_software_tar_name }}"
    validate_certs: no
    timeout: 600

- name: Unpackage the installer
  become: yes
  win_unzip:
    src: "{{ win_software_dest_folder }}\\{{ win_software_tar_name }}"
    remote_src: yes
    dest: "{{ win_install_path }}"
    creates: "{{ win_install_path }}\\{{ win_software_name }}\\"
  async: 3000
  poll: 60
  register: software_unzip_waiting

- name: Software unzip waiting
  become: yes
  async_status:
    jid: "{{ software_unzip_waiting.ansible_job_id }}"
  register: software_unzip_result
  until: software_unzip_result.finished
  retreis: 75

- name: Add software to the path
  become: yes
  win_environment:
    state: present
    name: "{{ win_software_name }}"
    value: "{{ win_install_path }}"
    level: machine

- name: Create Desktop Shortcut
  win_shortcut:
    src: "{{ win_install_path }}\\{{ win_software_name }}\\{{ win_software_exe }}"
    dest: "C:\\Users\\Public\\Desktop\\{{ win_link_name }}"

- name: Delete temp Directory
  become: yes
  win_file:
    path: "{{ win_software_dest_folder }}"
    state: absent

...
